# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf242a0455a747671a6499b6b3c5cbe4be203d99d763544500ec059f1ab3071d3a7a9b2a8d0a839ae7a2d818fce9c5b2c4ee0b808749a665512780dc036381c

test:
  secret_key_base: 0dbaef4b078431d7208c8d17334c5a6379dcea3da3a46e734691a7393504483764d2cacb9c6a7e9a69027d9550773846583595debef9ed2f6e4f2ae1bb3853fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
